development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DEVELOPMENT_DATABASE_USER'] %>
  #password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] %>
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['TEST_DATABASE_USER'] %>
  #password: <%= ENV['TEST_DATABASE_PASSWORD'] %>
production:
  adapter: sqlserver
  mode: dblib
  host: <%= ENV['AZURE_PRODUCTION_SERVER'] %>
  port: 1433
  database: <%= ENV['AZURE_PRODUCTION_DATABASE_NAME'] %>
  username: <%= ENV['AZURE_PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['AZURE_PRODUCTION_DATABASE_PASSWORD'] %>
  timeout: 5000
  azure: true