development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: "/opt/local/var/run/mysql5/mysqld.sock"