development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DEVELOPMENT_DATABASE_USER'] %>
  password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] %>
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['TEST_DATABASE_USER'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['PRODUCTION_DATABASE_USER'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>